name: Build and Test

on:
    push:
        branches: ["master"]

jobs:
    build-test-deploy:  
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code on master
          uses: actions/checkout@v4
        - name: Setup .Net
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Restore app dependencies
          run: dotnet restore
        - name: Build Project
          run: dotnet build --no-restore
        - name: Check PWD
          run: pwd
        - name: List PWD
          run: ls -al
        - name: Run unit Tests
          run: dotnet test --no-restore -v normal
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: us-west-2
        - name: Deploy application to Elastic Beanstalk
          uses: aws-actions/elastic-beanstalk-deploy@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            region: us-east-1
            application-name: bank-api
            environment-name: bank-api-env
            version-label: v1
  
        


